### ISSUE TITLE
`mlserver-mlflow`: Activating environment in the command results in failure when integrated 

### ISSUE THREAD

**Issue by orfeas-k** [canonical/seldonio-rocks#70]
### Bug Description

After adding the `source /hack/activate-env.sh ${MLSERVER_ENV_TARBALL} ` in the `command` field as upstream does [here](https://github.com/SeldonIO/MLServer/blob/1.3.5/Dockerfile#L120), the ROCK fails to start during integration tests with the following output

```
Defaulted container "classifier" out of: classifier, seldon-container-engine, classifier-model-initializer (init)
2023-12-12T10:15:05.442Z [pebble] Started daemon.
2023-12-12T10:15:05.447Z [pebble] POST /v1/services 4.247605ms 202
2023-12-12T10:15:05.448Z [pebble] Started default services with change 1.
2023-12-12T10:15:05.451Z [pebble] Service "mlserver-mlflow" starting: bash -c 'export PATH=/opt/conda/bin/:/opt/mlserver/.local/bin:${PATH}:/usr/bin && export PYTHONPATH=/opt/mlserver/.local/lib/python3.8/site-packages/:${PYTHONPATH} && eval $(/opt/conda/bin/conda shell.bash hook 2> /dev/null) && source /hack/activate-env.sh ${MLSERVER_ENV_TARBALL} && mlserver start ${MLSERVER_MODELS_DIR}'
2023-12-12T10:15:05.776Z [mlserver-mlflow] --> Unpacking environment at /mnt/models/environment.tar.gz...
2023-12-12T10:15:10.227Z [mlserver-mlflow] --> Sourcing new environment at ./envs/environment...
2023-12-12T10:15:10.248Z [mlserver-mlflow] --> Calling conda-unpack...
2023-12-12T10:15:10.592Z [mlserver-mlflow] --> Disabling user-installed packages...
2023-12-12T10:15:10.732Z [mlserver-mlflow] Traceback (most recent call last):
2023-12-12T10:15:10.732Z [mlserver-mlflow]   File "/opt/mlserver/envs/environment/bin/mlserver", line 5, in <module>
2023-12-12T10:15:10.732Z [mlserver-mlflow]     from mlserver.cli import main
2023-12-12T10:15:10.732Z [mlserver-mlflow]   File "/opt/mlserver/.local/lib/python3.8/site-packages/mlserver/__init__.py", line 2, in <module>
2023-12-12T10:15:10.732Z [mlserver-mlflow]     from .server import MLServer
2023-12-12T10:15:10.732Z [mlserver-mlflow]   File "/opt/mlserver/.local/lib/python3.8/site-packages/mlserver/server.py", line 7, in <module>
2023-12-12T10:15:10.732Z [mlserver-mlflow]     from mlserver.repository.factory import ModelRepositoryFactory
2023-12-12T10:15:10.732Z [mlserver-mlflow]   File "/opt/mlserver/.local/lib/python3.8/site-packages/mlserver/repository/__init__.py", line 1, in <module>
2023-12-12T10:15:10.732Z [mlserver-mlflow]     from .repository import (
2023-12-12T10:15:10.732Z [mlserver-mlflow]   File "/opt/mlserver/.local/lib/python3.8/site-packages/mlserver/repository/repository.py", line 9, in <module>
2023-12-12T10:15:10.732Z [mlserver-mlflow]     from ..errors import ModelNotFound
2023-12-12T10:15:10.732Z [mlserver-mlflow]   File "/opt/mlserver/.local/lib/python3.8/site-packages/mlserver/errors.py", line 1, in <module>
2023-12-12T10:15:10.732Z [mlserver-mlflow]     from fastapi import status
2023-12-12T10:15:10.732Z [mlserver-mlflow]   File "/opt/mlserver/.local/lib/python3.8/site-packages/fastapi/__init__.py", line 7, in <module>
2023-12-12T10:15:10.732Z [mlserver-mlflow]     from .applications import FastAPI as FastAPI
2023-12-12T10:15:10.732Z [mlserver-mlflow]   File "/opt/mlserver/.local/lib/python3.8/site-packages/fastapi/applications.py", line 15, in <module>
2023-12-12T10:15:10.732Z [mlserver-mlflow]     from fastapi import routing
2023-12-12T10:15:10.732Z [mlserver-mlflow]   File "/opt/mlserver/.local/lib/python3.8/site-packages/fastapi/routing.py", line 23, in <module>
2023-12-12T10:15:10.732Z [mlserver-mlflow]     from fastapi.datastructures import Default, DefaultPlaceholder
2023-12-12T10:15:10.732Z [mlserver-mlflow]   File "/opt/mlserver/.local/lib/python3.8/site-packages/fastapi/datastructures.py", line 3, in <module>
2023-12-12T10:15:10.732Z [mlserver-mlflow]     from starlette.datastructures import URL as URL  # noqa: F401
2023-12-12T10:15:10.732Z [mlserver-mlflow]   File "/opt/mlserver/.local/lib/python3.8/site-packages/starlette/datastructures.py", line 7, in <module>
2023-12-12T10:15:10.732Z [mlserver-mlflow]     from starlette.concurrency import run_in_threadpool
2023-12-12T10:15:10.732Z [mlserver-mlflow]   File "/opt/mlserver/.local/lib/python3.8/site-packages/starlette/concurrency.py", line 6, in <module>
2023-12-12T10:15:10.732Z [mlserver-mlflow]     import anyio
2023-12-12T10:15:10.732Z [mlserver-mlflow]   File "/opt/mlserver/.local/lib/python3.8/site-packages/anyio/__init__.py", line 21, in <module>
2023-12-12T10:15:10.732Z [mlserver-mlflow]     from ._core._fileio import AsyncFile as AsyncFile
2023-12-12T10:15:10.732Z [mlserver-mlflow]   File "/opt/mlserver/.local/lib/python3.8/site-packages/anyio/_core/_fileio.py", line 10, in <module>
2023-12-12T10:15:10.732Z [mlserver-mlflow]     from typing import (
2023-12-12T10:15:10.732Z [mlserver-mlflow] ImportError: cannot import name 'Final' from 'typing' (/opt/mlserver/envs/environment/lib/python3.7/typing.py)
2023-12-12T10:15:10.744Z [pebble] Service "mlserver-mlflow" stopped unexpectedly with code 1
2023-12-12T10:15:10.744Z [pebble] Service "mlserver-mlflow" on-failure action is "restart", waiting ~500ms before restart (backoff 1)
2023-12-12T10:15:11.248Z [pebble] Service "mlserver-mlflow" starting: bash -c 'export PATH=/opt/conda/bin/:/opt/mlserver/.local/bin:${PATH}:/usr/bin && export PYTHONPATH=/opt/mlserver/.local/lib/python3.8/site-packages/:${PYTHONPATH} && eval $(/opt/conda/bin/conda shell.bash hook 2> /dev/null) && source /hack/activate-env.sh ${MLSERVER_ENV_TARBALL} && mlserver start ${MLSERVER_MODELS_DIR}'
```

I cannot understand if this means that we use `Python3.8` interpreter(which we shouldn't) and try to use `Python3.7` libs or the other way around.

Note that we came across this now because before we didn't pass the proper arguments to `activate-env.sh` script which means that the script never ran and instead just logged
```
[mlserver-mlflow] Invalid number of arguments
[mlserver-mlflow] Usage: ./activate-env.sh <envTarball>
```

### To Reproduce

Add the `source /hack/activate-env.sh ${MLSERVER_ENV_TARBALL}` to the command and run ROCK's integration tests
```
tox -e pack
tox -e export-to-docker
tox -e integration
```
This will run `seldon-server-integration` test with `-k mlflowserver-v2` argument.

### Environment

- microk8s 1.25-strict/stable
- juju 3.1/stable

### Relevant Log Output
For reference, here's what **upstream image** logs during integration tests.
```shell
╰─$ kl mlflow-default-0-classifier-666d794cb-xw98v -f
Defaulted container "classifier" out of: classifier, seldon-container-engine, classifier-model-initializer (init)
--> Unpacking environment at /mnt/models/environment.tar.gz...
--> Sourcing new environment at ./envs/environment...
--> Calling conda-unpack...
--> Disabling user-installed packages...
INFO:     Started server process [1]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:9000 (Press CTRL+C to quit)
INFO:     192.168.2.3:37242 - "GET /v2/health/ready HTTP/1.1" 200 OK
```

### Additional Context

[rock-pip-freeze.txt](https://github.com/canonical/seldonio-rocks/files/13659284/rock-pip-freeze.txt)
[upstream-pip-freeze.txt](https://github.com/canonical/seldonio-rocks/files/13659286/upstream-pip-freeze.txt)

**Comment by orfeas-k** [comment]
### `mlserver-sklearn`
Adding this in this ROCK's command also resulted in the following errors
```
╰─$ kl sklearn-default-0-classifier-864547595b-m68nw
Defaulted container "classifier" out of: classifier, seldon-container-engine, classifier-model-initializer (init)
2023-12-13T11:48:50.028Z [pebble] Started daemon.
2023-12-13T11:48:50.032Z [pebble] POST /v1/services 3.575839ms 202
2023-12-13T11:48:50.032Z [pebble] Started default services with change 1.
2023-12-13T11:48:50.035Z [pebble] Service "mlserver-sklearn" starting: bash -c 'export PATH=/opt/conda/bin/:/opt/mlserver/.local/bin:${PATH}:/usr/bin && export PYTHONPATH=/opt/mlserver/.local/lib/python3.8/site-packages/:${PYTHONPATH} && eval $(/opt/conda/bin/conda shell.bash hook 2> /dev/null) && source /hack/activate-env.sh ${MLSERVER_ENV_TARBALL} && mlserver start ${MLSERVER_MODELS_DIR}'
2023-12-13T11:48:50.329Z [mlserver-sklearn] Environment tarball not found at '/mnt/models/environment.tar.gz'
2023-12-13T11:48:50.329Z [mlserver-sklearn] Environment not found at './envs/environment'
2023-12-13T11:48:51.631Z [mlserver-sklearn] Traceback (most recent call last):
2023-12-13T11:48:51.631Z [mlserver-sklearn]   File "/opt/mlserver/.local/bin/mlserver", line 8, in <module>
2023-12-13T11:48:51.631Z [mlserver-sklearn]     sys.exit(main())
2023-12-13T11:48:51.631Z [mlserver-sklearn]   File "/opt/mlserver/.local/lib/python3.8/site-packages/mlserver/cli/main.py", line 263, in main
2023-12-13T11:48:51.631Z [mlserver-sklearn]     root()
2023-12-13T11:48:51.631Z [mlserver-sklearn]   File "/opt/mlserver/.local/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
2023-12-13T11:48:51.631Z [mlserver-sklearn]     return self.main(*args, **kwargs)
2023-12-13T11:48:51.631Z [mlserver-sklearn]   File "/opt/mlserver/.local/lib/python3.8/site-packages/click/core.py", line 1078, in main
2023-12-13T11:48:51.631Z [mlserver-sklearn]     rv = self.invoke(ctx)
2023-12-13T11:48:51.631Z [mlserver-sklearn]   File "/opt/mlserver/.local/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
2023-12-13T11:48:51.631Z [mlserver-sklearn]     return _process_result(sub_ctx.command.invoke(sub_ctx))
2023-12-13T11:48:51.631Z [mlserver-sklearn]   File "/opt/mlserver/.local/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
2023-12-13T11:48:51.631Z [mlserver-sklearn]     return ctx.invoke(self.callback, **ctx.params)
2023-12-13T11:48:51.631Z [mlserver-sklearn]   File "/opt/mlserver/.local/lib/python3.8/site-packages/click/core.py", line 783, in invoke
2023-12-13T11:48:51.631Z [mlserver-sklearn]     return __callback(*args, **kwargs)
2023-12-13T11:48:51.631Z [mlserver-sklearn]   File "/opt/mlserver/.local/lib/python3.8/site-packages/mlserver/cli/main.py", line 23, in wrapper
2023-12-13T11:48:51.631Z [mlserver-sklearn]     return asyncio.run(f(*args, **kwargs))
2023-12-13T11:48:51.631Z [mlserver-sklearn]   File "/opt/conda/lib/python3.8/asyncio/runners.py", line 44, in run
2023-12-13T11:48:51.631Z [mlserver-sklearn]     return loop.run_until_complete(main)
2023-12-13T11:48:51.631Z [mlserver-sklearn]   File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
2023-12-13T11:48:51.631Z [mlserver-sklearn]   File "/opt/mlserver/.local/lib/python3.8/site-packages/mlserver/cli/main.py", line 46, in start
2023-12-13T11:48:51.631Z [mlserver-sklearn]     server = MLServer(settings)
2023-12-13T11:48:51.631Z [mlserver-sklearn]   File "/opt/mlserver/.local/lib/python3.8/site-packages/mlserver/server.py", line 32, in __init__
2023-12-13T11:48:51.631Z [mlserver-sklearn]     self._metrics_server = MetricsServer(self._settings)
2023-12-13T11:48:51.631Z [mlserver-sklearn]   File "/opt/mlserver/.local/lib/python3.8/site-packages/mlserver/metrics/server.py", line 25, in __init__
2023-12-13T11:48:51.631Z [mlserver-sklearn]     self._app = self._get_app()
2023-12-13T11:48:51.631Z [mlserver-sklearn]   File "/opt/mlserver/.local/lib/python3.8/site-packages/mlserver/metrics/server.py", line 28, in _get_app
2023-12-13T11:48:51.631Z [mlserver-sklearn]     app = FastAPI(debug=self._settings.debug)
2023-12-13T11:48:51.631Z [mlserver-sklearn]   File "/opt/mlserver/.local/lib/python3.8/site-packages/fastapi/applications.py", line 146, in __init__
2023-12-13T11:48:51.631Z [mlserver-sklearn]     self.middleware_stack: ASGIApp = self.build_middleware_stack()
2023-12-13T11:48:51.631Z [mlserver-sklearn]   File "/opt/mlserver/.local/lib/python3.8/site-packages/fastapi/applications.py", line 152, in build_middleware_stack
2023-12-13T11:48:51.631Z [mlserver-sklearn]     debug = self.debug
2023-12-13T11:48:51.631Z [mlserver-sklearn] AttributeError: 'FastAPI' object has no attribute 'debug'
2023-12-13T11:48:51.771Z [pebble] Service "mlserver-sklearn" stopped unexpectedly with code 1
2023-12-13T11:48:51.771Z [pebble] Service "mlserver-sklearn" on-failure action is "restart", waiting ~500ms before restart (backoff 1)
```

Maybe there is something I miss from those ROCKs design and we indeed do not need this because we 're already running in the proper environment.

**Comment by orfeas-k** [comment]
The above issue doesn't stand anymore. This was caused by the fact that running `rockcraft clean && rockcraft pack` with the rockcraft.yaml pack didn't result in the same dependencies in the built images (as described in https://github.com/canonical/seldonio-rocks/issues/80#issuecomment-1886997338). With that being said, we indeed removed the `source /hack/activate-env.sh ${MLSERVER_ENV_TARBALL}` part of the command due to https://github.com/canonical/seldonio-rocks/issues/37#issuecomment-1886962552.
